<?php

/**
 * @file
 * Contains thingy.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function thingy_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the thingy module.
    case 'help.page.thingy':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Thingy Entity Example') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
/*function thingy_theme() {
  return [
    'thingy' => [
      'render element' => 'children',
    ],
  ];
}*/

/**
 * Implements hook_theme().
 */
function thingy_theme() {
  $theme = [];
  $theme['thingy'] = [
    'render element' => 'elements',
    'file' => 'thingy.page.inc',
    'template' => 'thingy',
  ];
  $theme['thingy_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'thingy.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function thingy_theme_suggestions_thingy(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#thingy'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'thingy__' . $sanitized_view_mode;
  $suggestions[] = 'thingy__' . $entity->bundle();
  $suggestions[] = 'thingy__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'thingy__' . $entity->id();
  $suggestions[] = 'thingy__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
